### ISSUE TITLE
Crear estructura de carpetas correcta

### ISSUE THREAD

**Issue by Albametnet** [Adalab/s4-interacso#1]
Aunque la estructura de carpetas con sass y componentes solemos hacerla en un comienzo hoy por motivos de organización hacemos archivos sueltos. Mañana (5/9) debemos resolver eso antes de crear mas archivos y incluir cada uno donde corresponda.

**Comment by oneeyedman** [comment]
@Albametnet igual que en el otro issue. Asigna a una persona solo, no a todo el equipo
